### ISSUE TITLE
[IE11] Automatic publicPath is not supported in this browser

### ISSUE THREAD

**Issue by shtbik** [hasanayan/craco-module-federation#7]
Checked my app in IE11 and got `Automatic publicPath is not supported in this browser`
Also, didn't find a way to rewrite [this line](https://github.com/hasanayan/craco-module-federation/blob/main/index.js#L25), looks that craco runs plugins after `webpack.configure`
Tried different options from [official docs](https://webpack.js.org/guides/public-path/#root) but get this exception earlier than a workaround is executed

Please suggest a way to avoid the error

```
"@craco/craco": "^6.4.0"
"craco-module-federation": "^1.1.0"
"react-scripts": "^5.0.0"
Win10
IE 11.379.17763.0
```

<img width="1089" alt="Screen Shot 2022-01-11 at 4 59 44 pm" src="https://user-images.githubusercontent.com/12717213/148895872-5b5ace9c-0e3a-4bd2-9a22-e259161b2346.png">

**Comment by hasanayan** [comment]
umm get rid of E11 support? lol

**Comment by shtbik** [comment]
As a workaround, I used the rewrite plugin:
```
plugins: [
      {
        plugin: cracoModuleFederation,
      },
      {
        plugin: {
          overrideWebpackConfig: ({ webpackConfig }) => {
            webpackConfig.output.publicPath = '/test/';
            return webpackConfig;
          },
        },
      }
]
```
I guess it could be helpful to add the ability to pass some options like `publicPath` into `cracoModuleFederation`
